export const SENDMESSAGE = 'SENDMESSAGE';
export const CREATECONTACT = 'CREATECONTACT';
export const AUTHCONTACT = 'AUTHCONTACT';
export const LOGOUTCONTACT = 'LOGOUTCONTACT';
export const CHECKCONTACT = 'CHECKCONTACT';
export const SEARCHCONTACT = 'SEARCHCONTACT';
export const CURRENTRECEIVER = 'CURRENTRECEIVER';
export const GETMESSAGES = 'GETMESSAGES';